   193.8ms (setup:858): 2024-11-22 18:01:55
   193.9ms (setup:859): /usr/bin/pipx install django-cors-headers
   193.9ms (setup:860): pipx version is 1.4.3
   194.0ms (setup:861): Default python interpreter is '/usr/bin/python3'
   195.6ms (package_name_from_spec:370): Determined package name: django-cors-headers
   195.6ms (package_name_from_spec:371): Package name determined in 0.0s
   196.7ms (run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /home/ilia/.local/share/pipx/venvs/django-cors-headers
   270.5ms (run_subprocess:190): stdout:
   270.6ms (run_subprocess:192): stderr:
   270.6ms (run_subprocess:193): returncode: 0
   271.3ms (run_subprocess:168): running <checking pip's availability>
   298.3ms (run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f4f2911fe60>, origin='/home/ilia/.local/share/pipx/shared/lib/python3.12/site-packages/pip/__init__.py', submodule_search_locations=['/home/ilia/.local/share/pipx/shared/lib/python3.12/site-packages/pip'])
   298.4ms (run_subprocess:193): returncode: 0
   298.6ms (run_subprocess:168): running /home/ilia/.local/share/pipx/venvs/django-cors-headers/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   328.1ms (run_subprocess:190): stdout: /home/ilia/.local/share/pipx/venvs/django-cors-headers/lib/python3.12/site-packages
   328.2ms (run_subprocess:193): returncode: 0
   328.4ms (run_subprocess:168): running /home/ilia/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   356.9ms (run_subprocess:190): stdout: /home/ilia/.local/share/pipx/shared/lib/python3.12/site-packages
   357.0ms (run_subprocess:193): returncode: 0
   357.4ms (run_subprocess:168): running /home/ilia/.local/share/pipx/venvs/django-cors-headers/bin/python --version
   359.2ms (run_subprocess:190): stdout: Python 3.12.3
   359.3ms (run_subprocess:192): stderr:
   359.4ms (run_subprocess:193): returncode: 0
   359.6ms (_parsed_package_to_package_or_url:137): cleaned package spec: django-cors-headers
   360.3ms (run_subprocess:168): running /home/ilia/.local/share/pipx/venvs/django-cors-headers/bin/python -m pip --no-input install django-cors-headers
  6612.2ms (run_subprocess:193): returncode: 0
  6613.6ms (run_subprocess:168): running <fetch_info_in_venv commands>
  6669.5ms (run_subprocess:190): stdout: {"sys_path": ["/usr/lib/python312.zip", "/usr/lib/python3.12", "/usr/lib/python3.12/lib-dynload", "/home/ilia/.local/share/pipx/venvs/django-cors-headers/lib/python3.12/site-packages", "/home/ilia/.local/share/pipx/shared/lib/python3.12/site-packages"], "python_version": "3.12.3", "environment": {"implementation_name": "cpython", "implementation_version": "3.12.3", "os_name": "posix", "platform_machine": "x86_64", "platform_release": "5.15.167.4-microsoft-standard-WSL2", "platform_system": "Linux", "platform_version": "#1 SMP Tue Nov 5 00:21:55 UTC 2024", "python_full_version": "3.12.3", "platform_python_implementation": "CPython", "python_version": "3.12", "sys_platform": "linux"}}
  6669.6ms (run_subprocess:193): returncode: 0
  7039.2ms (get_venv_metadata_for_package:339): get_venv_metadata_for_package: 426ms
  7039.5ms (_parsed_package_to_package_or_url:137): cleaned package spec: django-cors-headers
  7040.2ms (rmdir:55): removing directory /home/ilia/.local/share/pipx/venvs/django-cors-headers
  7433.6ms (cli:924): PipxError: No apps associated with package django-cors-headers. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you
are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 100, in install
    run_post_install_actions(
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 427, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package django-cors-headers. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you
are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
  7435.7ms (cli:932): pipx finished.
